backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    folder: src/blog
    create: true
    format: mdx
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: datetimes
      - name: body
        label: Body
        widget: markdown
