backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/blog"
    create: true
    slug: "{"{title}"}_{"{year}}-{{month}}-{{day}"}_{"{slug}"}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: 'slug', label: 'Slug', widget: 'string' }
      - { name: "body", label: "Body", widget: "markdown" }