backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

publish_mode: "editorial_workflow"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blogpost" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: false, format: "YYYY MMM Do" }
      - { label: "Slug", name: "slug", encoding: "ascii", required: true, widget: "string", hint: "remember-to-use-lowercase-and-dashes" }
      - { label: "Body", name: "body", widget: "markdown" }
